/**
* This file was @generated by pocketbase-typegen based on your schema.
*/

export enum Collections {
    BakeryInfo = "bakery_info",
    Categories = "categories",
    InventoryLogs = "inventory_logs",
    OrderItems = "order_items",
    Orders = "orders",
    Products = "products",
    Suppliers = "suppliers",
    Supplies = "supplies",
    Users = "users",
}

// Alias types for convenience
export type AuthSystemFields<T = never> = {
    id: string
    created: string
    updated: string
    collectionId: string
    collectionName: Collections
    expand?: T
}

export type BaseSystemFields<T = never> = {
    id: string
    created: string
    updated: string
    collectionId: string
    collectionName: Collections
    expand?: T
}

// Record types for each collection

export type BakeryInfoRecord = {
    name: string
    description?: string
    logo?: string
}

export type CategoriesRecord = {
    name: string
    type?: "product" | "supply"
}

export type InventoryLogsRecord = {
    product?: string
    supply?: string
    reason: "sale" | "waste" | "restock" | "adjustment"
    quantity: number
    user?: string
}

export type OrderItemsRecord = {
    order: string
    product: string
    quantity: number
    price: number
    subtotal: number
}

export type OrdersRecord = {
    total: number
    cashier: string
    status?: "completed" | "cancelled"
}

export type ProductsRecord = {
    name: string
    description?: string
    unit?: "kg" | "g" | "mL" | "L" | "pcs"
    stock?: number
    category: string
    images?: string[]
    price: number
    active?: boolean
}

export type SuppliersRecord = {
    name: string
    contact_person?: string
    phone?: string
    email?: string
    categories?: string[]
    logo?: string
}

export type SuppliesRecord = {
    name: string
    description?: string
    unit?: "kg" | "g" | "mL" | "L" | "pcs"
    current_stock?: number
    min_stock?: number
    max_stock?: number
    category?: string
    images?: string[]
}

export type UsersRecord = {
    name?: string
    avatar?: string
}

// Response types (Record + System Fields)

export type BakeryInfoResponse<Texpand = unknown> = Required<BakeryInfoRecord> & BaseSystemFields<Texpand>
export type CategoriesResponse<Texpand = unknown> = Required<CategoriesRecord> & BaseSystemFields<Texpand>
export type InventoryLogsResponse<Texpand = unknown> = Required<InventoryLogsRecord> & BaseSystemFields<Texpand>
export type OrderItemsResponse<Texpand = unknown> = Required<OrderItemsRecord> & BaseSystemFields<Texpand>
export type OrdersResponse<Texpand = unknown> = Required<OrdersRecord> & BaseSystemFields<Texpand>
export type ProductsResponse<Texpand = unknown> = Required<ProductsRecord> & BaseSystemFields<Texpand>
export type SuppliersResponse<Texpand = unknown> = Required<SuppliersRecord> & BaseSystemFields<Texpand>
export type SuppliesResponse<Texpand = unknown> = Required<SuppliesRecord> & BaseSystemFields<Texpand>
export type UsersResponse<Texpand = unknown> = Required<UsersRecord> & AuthSystemFields<Texpand>

// Overall type for all collection responses
export type CollectionResponses = {
    bakery_info: BakeryInfoResponse
    categories: CategoriesResponse
    inventory_logs: InventoryLogsResponse
    order_items: OrderItemsResponse
    orders: OrdersResponse
    products: ProductsResponse
    suppliers: SuppliersResponse
    supplies: SuppliesResponse
    users: UsersResponse
}

export type CollectionRecords = {
    bakery_info: BakeryInfoRecord
    categories: CategoriesRecord
    inventory_logs: InventoryLogsRecord
    order_items: OrderItemsRecord
    orders: OrdersRecord
    products: ProductsRecord
    suppliers: SuppliersRecord
    supplies: SuppliesRecord
    users: UsersRecord
}